Add GitHub release workflow
ballerina-platform/module-ballerinax-kafka pull request #34
Opened 2020-09-21 16:32 UTC by aashikam

## Purpose
$title

2020-09-21 16:42 UTC, ThisaruGuruge approved these changes

2020-09-21 17:25 UTC, niveathika requested changes

2020-09-21 17:25 UTC, niveathika commented on .github/workflows/publish-release.yaml
> +                        bin/hub pull-request -m "[Automated] Sync master after "$VERSION" release"
Wrong indentation

2020-09-21 17:31 UTC, BuddhiWathsala commented on .github/workflows/daily-build.yaml
> +              run: ./gradlew.bat build -x test
Do we need this here since the daily builds are passing?

2020-09-22 03:11 UTC, niveathika approved these changes

2020-09-22 03:11 UTC, merged